### ISSUE TITLE
Space in image path makes it irrecognizable 

### ISSUE THREAD

**Issue by Unknow0059** [alvesjtiago/hover-preview#43]
Hovering on the following address in Sublime with this package installed _**G:\tumblr_inline_p7j0hwUKc51ri065t_400Copy.gif**_ makes the image hover-appear as intended, but doing so with _**G:\pixeldigest tumblr_inline_p7j0hwUKc51ri065t_400.gif**_ does not.

I assume this is because the whitespace character makes images irrecognizable. 

If I'm right; are there plans to resolve this? If I'm wrong, then I have no idea what the issue is.

**Comment by AmjadHD** [comment]
yes this is because of the whitespace character, the plugin have to handle a lot of image identifiers:
https://github.com/alvesjtiago/hover-preview/blob/8fb105c0ac24d9480f888bbd2ab3c240a1cd1d93/main.py#L61-L72

**Comment by alvesjtiago** [comment]
@Unknow0059 supporting paths with whitespaces is not on the current roadmap since it doesn't translate well to most development flows or deployment options. Is there a specific reason why you'd like to support that?

Closing it for now but will consider opening in the future if there's a valid reason or more people looking to have this feature supported (it will also impact negatively the performance of the plugin). Hope you understand @Unknow0059 and that this isn't a deal breaker for you to continue using Image Preview 😊

**Comment by Unknow0059** [comment]
The reason is that I have lots of folders and files in my Windows directories that have spaces in them.
It's not a deal-breaker because this is the only plugin that exists for Sublime that can do what it does, as far as I know.
If by "negatively impact the performance" you mean that it would have trouble finding the image, I would be fine with fully selecting the image path with the mouse, but if you mean that adding whitespace support, in general, would cause this, well... in that case, I guess not much can be done about it.

**Comment by alvesjtiago** [comment]
In order to account for whitespaces it would be necessary to verify all possible combinations of words and check if there's an image that corresponds to it which wouldn't be efficient on runtime.

The idea of selecting the path and hovering the selected text is an interesting one. I'll open a ticket with this request and mention you right after the name of the plugin is changed.

**Comment by Unknow0059** [comment]
This is unrelated to the issue but I don't feel the need to open up a new one - would it be too difficult to make paths recognized by the plugin be hightlighted with some color? I commonly use plain text, and it's hard to find, at a glance, previewable links.

It is completely understandable if not, as this is in no way critical.

**Comment by 9840380** [comment]
you can try to modify regex like this adding \s

                               r"(?:[-.@\w\s]+?[\\/])*"                   # body
                               r"[-.@\w\s]+?"                             # name

**Comment by 9840380** [comment]
> Hovering on the following address in Sublime with this package installed _**G:\tumblr_inline_p7j0hwUKc51ri065t_400Copy.gif**_ makes the image hover-appear as intended, but doing so with _**G:\pixeldigest tumblr_inline_p7j0hwUKc51ri065t_400.gif**_ does not.
> 
> I assume this is because the whitespace character makes images irrecognizable.
> 
> If I'm right; are there plans to resolve this? If I'm wrong, then I have no idea what the issue is.

You can try to modify regex like this, adding \s

                               r"(?:[-.@\w\s]+?[\\/])*"                   # body
                               r"[-.@\w\s]+?"                             # name

**Comment by Unknow0059** [comment]
> 
> You can try to modify regex like this, adding \s
> 
> ```
>                            r"(?:[-.@\w\s]+?[\\/])*"                   # body
>                            r"[-.@\w\s]+?"                             # name
> ```

Can't you try? You're suggesting it.

**Comment by 9840380** [comment]
> > You can try to modify regex like this, adding \s
> > ```
> >                            r"(?:[-.@\w\s]+?[\\/])*"                   # body
> >                            r"[-.@\w\s]+?"                             # name
> > ```
> 
> Can't you try? You're suggesting it.

yep
<img width="1280" alt="Screenshot 2024-05-16 at 10 41 49" src="https://github.com/alvesjtiago/hover-preview/assets/33433075/fa796d60-b155-4afb-abc8-9ae8a74e8a50">

**Comment by 9840380** [comment]
only issue is with Cyrillic symbols in text
